# Site settings
permalink: /:year/:month/:day/:title.html
title: Kdqzzxxcc
email: kongdq1992@gmail.com
description: Just Do It
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kdqzzxxcc.github.io" # the base hostname & protocol for your site
github_username:  kdqzzxxcc

# Build settings
markdown: kramdown
